// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.Build.ObjectModelRemoting;
using Microsoft.EntityFrameworkCore;

namespace ERP_BI_Operations.Models;

public partial class Account
{
    [Key]
    [Column("AccountID")]
    public int AccountId { get; set; }

    public decimal Balance { get; set; }

    [Required]
    [StringLength(255)]
    public string AccountName { get; set; }

    [StringLength(100)]
    public string AccountType { get; set; }

    [Column("CompanyID")]
    public int CompanyId { get; set; }

    [ForeignKey("CompanyId")]
    [InverseProperty("Accounts")]
    public virtual Company Company { get; set; }

    [InverseProperty("Account")]
    public virtual ICollection<JournalEntryLine> JournalEntryLines { get; set; } = new List<JournalEntryLine>();
}