// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ERP_BI_Operations.Models;

[Table("APInvoices")]
public partial class Apinvoice
{
    [Key]
    [Column("APInvoiceID")]
    public int ApinvoiceId { get; set; }

    [Column("VendorID")]
    public int VendorId { get; set; }

    [Column("ProjectID")]
    public int? ProjectId { get; set; }

    public DateOnly InvoiceDate { get; set; }

    public DateOnly? DueDate { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal Amount { get; set; }

    [StringLength(50)]
    public string Status { get; set; }

    public string Description { get; set; }

    [InverseProperty("Apinvoice")]
    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();

    [ForeignKey("ProjectId")]
    [InverseProperty("Apinvoices")]
    public virtual Project Project { get; set; }

    [ForeignKey("VendorId")]
    [InverseProperty("Apinvoices")]
    public virtual Vendor Vendor { get; set; }
}