// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ERP_BI_Operations.Models;

[Table("ARInvoices")]
public partial class Arinvoice
{
    [Key]
    [Column("ARInvoiceID")]
    public int ArinvoiceId { get; set; }

    [Column("CustomerID")]
    public int CustomerId { get; set; }

    [Column("ProjectID")]
    public int? ProjectId { get; set; }

    public DateOnly InvoiceDate { get; set; }

    public DateOnly? DueDate { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal Amount { get; set; }

    [StringLength(50)]
    public string Status { get; set; }

    public string Description { get; set; }

    [ForeignKey("CustomerId")]
    [InverseProperty("Arinvoices")]
    public virtual Customer Customer { get; set; }

    [ForeignKey("ProjectId")]
    [InverseProperty("Arinvoices")]
    public virtual Project Project { get; set; }

    [InverseProperty("Arinvoice")]
    public virtual ICollection<Receipt> Receipts { get; set; } = new List<Receipt>();
}