// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ERP_BI_Operations.Models;

public partial class BankAccount
{
    [Key]
    [Column("BankID")]
    public int BankId { get; set; }

    [Required]
    [StringLength(255)]
    public string AccountName { get; set; }

    [Required]
    [StringLength(255)]
    public string AccountNumber { get; set; }

    [StringLength(255)]
    public string BankName { get; set; }

    [Column("CompanyID")]
    public int CompanyId { get; set; }

    [ForeignKey("CompanyId")]
    [InverseProperty("BankAccounts")]
    public virtual Company Company { get; set; }

    [InverseProperty("Bank")]
    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();

    [InverseProperty("Bank")]
    public virtual ICollection<Receipt> Receipts { get; set; } = new List<Receipt>();
}