// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ERP_BI_Operations.Models;

public partial class Customer
{
    [Key]
    [Column("CustomerID")]
    public int CustomerId { get; set; }

    [Required]
    [StringLength(255)]
    public string CustomerName { get; set; }

    [StringLength(255)]
    public string ContactPerson { get; set; }

    [StringLength(255)]
    public string Address { get; set; }

    [StringLength(100)]
    public string BillingTerms { get; set; }

    [Column("CompanyID")]
    public int CompanyId { get; set; }

    [InverseProperty("Customer")]
    public virtual ICollection<Arinvoice> Arinvoices { get; set; } = new List<Arinvoice>();

    [ForeignKey("CompanyId")]
    [InverseProperty("Customers")]
    public virtual Company Company { get; set; }

    [InverseProperty("Customer")]
    public virtual ICollection<Project> Projects { get; set; } = new List<Project>();

    [InverseProperty("Customer")]
    public virtual ICollection<ServiceAgreement> ServiceAgreements { get; set; } = new List<ServiceAgreement>();

    [InverseProperty("Customer")]
    public virtual ICollection<ServiceOrder> ServiceOrders { get; set; } = new List<ServiceOrder>();
}