// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ERP_BI_Operations.Models;

public partial class Document
{
    [Key]
    [Column("DocumentID")]
    public int DocumentId { get; set; }

    [Required]
    [StringLength(255)]
    public string DocumentName { get; set; }

    [StringLength(100)]
    public string DocumentType { get; set; }

    [Column("FilePathURL")]
    [StringLength(255)]
    public string FilePathUrl { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UploadDate { get; set; }

    [Column("ProjectID")]
    public int? ProjectId { get; set; }

    [ForeignKey("ProjectId")]
    [InverseProperty("Documents")]
    public virtual Project Project { get; set; }
}