// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ERP_BI_Operations.Models;

public partial class Employee
{
    [Key]
    [Column("EmployeeID")]
    public int EmployeeId { get; set; }

    [Required]
    [StringLength(255)]
    public string FirstName { get; set; }

    [Required]
    [StringLength(255)]
    public string LastName { get; set; }

    public DateOnly? DateOfHire { get; set; }

    [StringLength(255)]
    public string JobTitle { get; set; }

    [StringLength(255)]
    public string ContactInfo { get; set; }

    [Column("DepartmentID")]
    public int? DepartmentId { get; set; }

    [Column("CompanyID")]
    public int CompanyId { get; set; }

    [ForeignKey("CompanyId")]
    [InverseProperty("Employees")]
    public virtual Company Company { get; set; }

    [ForeignKey("DepartmentId")]
    [InverseProperty("Employees")]
    public virtual Department Department { get; set; }

    [InverseProperty("Employee")]
    public virtual ICollection<EmployeePayDetail> EmployeePayDetails { get; set; } = new List<EmployeePayDetail>();

    [InverseProperty("Operator")]
    public virtual ICollection<EquipmentUsage> EquipmentUsages { get; set; } = new List<EquipmentUsage>();

    [InverseProperty("PerformedByNavigation")]
    public virtual ICollection<MaintenanceRecord> MaintenanceRecords { get; set; } = new List<MaintenanceRecord>();

    [InverseProperty("ProjectManager")]
    public virtual ICollection<Project> Projects { get; set; } = new List<Project>();

    [InverseProperty("RequestedByNavigation")]
    public virtual ICollection<Rfi> Rfis { get; set; } = new List<Rfi>();

    [InverseProperty("AssignedTechnician")]
    public virtual ICollection<ServiceOrder> ServiceOrders { get; set; } = new List<ServiceOrder>();

    [InverseProperty("Employee")]
    public virtual ICollection<TimeEntry> TimeEntries { get; set; } = new List<TimeEntry>();

    [InverseProperty("SentByNavigation")]
    public virtual ICollection<Transmittal> Transmittals { get; set; } = new List<Transmittal>();

    [InverseProperty("Employee")]
    public virtual ICollection<User> Users { get; set; } = new List<User>();
}