// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ERP_BI_Operations.Models;

[Index("SerialNumber", Name = "UQ__Equipmen__048A0008FFB9B8D0", IsUnique = true)]
public partial class Equipment
{
    [Key]
    [Column("EquipmentID")]
    public int EquipmentId { get; set; }

    [Required]
    [StringLength(255)]
    public string EquipmentName { get; set; }

    [StringLength(255)]
    public string SerialNumber { get; set; }

    public DateOnly? PurchaseDate { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? PurchaseCost { get; set; }

    [StringLength(255)]
    public string CurrentLocation { get; set; }

    [StringLength(50)]
    public string Status { get; set; }

    [Column("CompanyID")]
    public int CompanyId { get; set; }

    [ForeignKey("CompanyId")]
    [InverseProperty("Equipment")]
    public virtual Company Company { get; set; }

    [InverseProperty("Equipment")]
    public virtual ICollection<EquipmentUsage> EquipmentUsages { get; set; } = new List<EquipmentUsage>();

    [InverseProperty("Equipment")]
    public virtual ICollection<MaintenanceRecord> MaintenanceRecords { get; set; } = new List<MaintenanceRecord>();
}