// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ERP_BI_Operations.Models;

[Table("EquipmentUsage")]
public partial class EquipmentUsage
{
    [Key]
    [Column("UsageID")]
    public int UsageId { get; set; }

    [Column("EquipmentID")]
    public int EquipmentId { get; set; }

    [Column("ProjectID")]
    public int? ProjectId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime StartDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? EndDate { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal? UsageHours { get; set; }

    [StringLength(50)]
    public string UsageUnits { get; set; }

    [Column("OperatorID")]
    public int? OperatorId { get; set; }

    [ForeignKey("EquipmentId")]
    [InverseProperty("EquipmentUsages")]
    public virtual Equipment Equipment { get; set; }

    [ForeignKey("OperatorId")]
    [InverseProperty("EquipmentUsages")]
    public virtual Employee Operator { get; set; }

    [ForeignKey("ProjectId")]
    [InverseProperty("EquipmentUsages")]
    public virtual Project Project { get; set; }
}