// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ERP_BI_Operations.Models;

public partial class FinancialSnapshot
{
    [Key]
    [Column("SnapshotID")]
    public int SnapshotId { get; set; }

    public DateOnly SnapshotDate { get; set; }

    [Column("CompanyID")]
    public int CompanyId { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? TotalRevenue { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? TotalExpenses { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? NetProfit { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? CashBalance { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? AccountsReceivableBalance { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? AccountsPayableBalance { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? PayrollCost { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? EquipmentCost { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? MaterialCost { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? OtherFinancialMetric1 { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? OtherFinancialMetric2 { get; set; }

    [ForeignKey("CompanyId")]
    [InverseProperty("FinancialSnapshots")]
    public virtual Company Company { get; set; }
}