// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ERP_BI_Operations.Models;

public partial class ForecastedFinancial
{
    [Key]
    [Column("ForecastID")]
    public int ForecastId { get; set; }

    public DateOnly ForecastDate { get; set; }

    public DateOnly TargetDate { get; set; }

    [Column("CompanyID")]
    public int CompanyId { get; set; }

    [Column("ProjectID")]
    public int? ProjectId { get; set; }

    [Required]
    [StringLength(100)]
    public string ForecastType { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? ForecastedValue { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? ConfidenceIntervalLow { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? ConfidenceIntervalHigh { get; set; }

    [StringLength(255)]
    public string ModelUsed { get; set; }

    [ForeignKey("CompanyId")]
    [InverseProperty("ForecastedFinancials")]
    public virtual Company Company { get; set; }

    [ForeignKey("ProjectId")]
    [InverseProperty("ForecastedFinancials")]
    public virtual Project Project { get; set; }
}