// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ERP_BI_Operations.Models;

public partial class JournalEntry
{
    [Key]
    [Column("JournalEntryID")]
    public int JournalEntryId { get; set; }

    public DateOnly EntryDate { get; set; }

    public string Description { get; set; }

    [Column("CompanyID")]
    public int CompanyId { get; set; }

    [ForeignKey("CompanyId")]
    [InverseProperty("JournalEntries")]
    public virtual Company Company { get; set; }

    [InverseProperty("JournalEntry")]
    public virtual ICollection<JournalEntryLine> JournalEntryLines { get; set; } = new List<JournalEntryLine>();
}