// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ERP_BI_Operations.Models;

public partial class JournalEntryLine
{
    [Key]
    [Column("JournalEntryLineID")]
    public int JournalEntryLineId { get; set; }

    [Column("JournalEntryID")]
    public int JournalEntryId { get; set; }

    [Column("AccountID")]
    public int AccountId { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? DebitAmount { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? CreditAmount { get; set; }

    [ForeignKey("AccountId")]
    [InverseProperty("JournalEntryLines")]
    public virtual Account Account { get; set; }

    [ForeignKey("JournalEntryId")]
    [InverseProperty("JournalEntryLines")]
    public virtual JournalEntry JournalEntry { get; set; }
}