// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ERP_BI_Operations.Models;

[Table("KPIs")]
public partial class Kpi
{
    [Key]
    [Column("KPIID")]
    public int Kpiid { get; set; }

    [Required]
    [Column("KPIName")]
    [StringLength(255)]
    public string Kpiname { get; set; }

    [Column("KPIDate")]
    public DateOnly Kpidate { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? Value { get; set; }

    [Column("CompanyID")]
    public int CompanyId { get; set; }

    [Column("ProjectID")]
    public int? ProjectId { get; set; }

    [ForeignKey("CompanyId")]
    [InverseProperty("Kpis")]
    public virtual Company Company { get; set; }

    [ForeignKey("ProjectId")]
    [InverseProperty("Kpis")]
    public virtual Project Project { get; set; }
}