// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ERP_BI_Operations.Models;

public partial class MaintenanceRecord
{
    [Key]
    [Column("MaintenanceID")]
    public int MaintenanceId { get; set; }

    [Column("EquipmentID")]
    public int EquipmentId { get; set; }

    public DateOnly MaintenanceDate { get; set; }

    public string Description { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? Cost { get; set; }

    public int? PerformedBy { get; set; }

    [StringLength(100)]
    public string MaintenanceType { get; set; }

    [ForeignKey("EquipmentId")]
    [InverseProperty("MaintenanceRecords")]
    public virtual Equipment Equipment { get; set; }

    [ForeignKey("PerformedBy")]
    [InverseProperty("MaintenanceRecords")]
    public virtual Employee PerformedByNavigation { get; set; }
}