// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ERP_BI_Operations.Models;

public partial class Material
{
    [Key]
    [Column("MaterialID")]
    public int MaterialId { get; set; }

    [Required]
    [StringLength(255)]
    public string MaterialName { get; set; }

    [StringLength(50)]
    public string UnitOfMeasure { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal? CurrentStock { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal? ReorderLevel { get; set; }

    [Column("CompanyID")]
    public int CompanyId { get; set; }

    [ForeignKey("CompanyId")]
    [InverseProperty("Materials")]
    public virtual Company Company { get; set; }

    [InverseProperty("Material")]
    public virtual ICollection<MaterialUsage> MaterialUsages { get; set; } = new List<MaterialUsage>();

    [InverseProperty("Material")]
    public virtual ICollection<PurchaseOrderLine> PurchaseOrderLines { get; set; } = new List<PurchaseOrderLine>();
}