// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ERP_BI_Operations.Models;

[Table("MaterialUsage")]
public partial class MaterialUsage
{
    [Key]
    [Column("MaterialUsageID")]
    public int MaterialUsageId { get; set; }

    [Column("ProjectID")]
    public int ProjectId { get; set; }

    [Column("MaterialID")]
    public int MaterialId { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal QuantityUsed { get; set; }

    public DateOnly UsageDate { get; set; }

    [ForeignKey("MaterialId")]
    [InverseProperty("MaterialUsages")]
    public virtual Material Material { get; set; }

    [ForeignKey("ProjectId")]
    [InverseProperty("MaterialUsages")]
    public virtual Project Project { get; set; }
}