// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ERP_BI_Operations.Models;

public partial class Payment
{
    [Key]
    [Column("PaymentID")]
    public int PaymentId { get; set; }

    [Column("APInvoiceID")]
    public int ApinvoiceId { get; set; }

    [Column("BankID")]
    public int BankId { get; set; }

    public DateOnly PaymentDate { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal Amount { get; set; }

    [StringLength(100)]
    public string PaymentMethod { get; set; }

    [ForeignKey("ApinvoiceId")]
    [InverseProperty("Payments")]
    public virtual Apinvoice Apinvoice { get; set; }

    [ForeignKey("BankId")]
    [InverseProperty("Payments")]
    public virtual BankAccount Bank { get; set; }
}