// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ERP_BI_Operations.Models;

public partial class PayrollRun
{
    [Key]
    [Column("PayrollRunID")]
    public int PayrollRunId { get; set; }

    public DateOnly PayPeriodStart { get; set; }

    public DateOnly PayPeriodEnd { get; set; }

    public DateOnly RunDate { get; set; }

    [StringLength(50)]
    public string Status { get; set; }

    [Column("CompanyID")]
    public int CompanyId { get; set; }

    [ForeignKey("CompanyId")]
    [InverseProperty("PayrollRuns")]
    public virtual Company Company { get; set; }

    [InverseProperty("PayrollRun")]
    public virtual ICollection<EmployeePayDetail> EmployeePayDetails { get; set; } = new List<EmployeePayDetail>();
}