// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ERP_BI_Operations.Models;

public partial class Project
{
    [Key]
    [Column("ProjectID")]
    public int ProjectId { get; set; }

    [Required]
    [StringLength(255)]
    public string ProjectName { get; set; }

    [Column("ProjectManagerID")]
    public int? ProjectManagerId { get; set; }

    [Column("CustomerID")]
    public int? CustomerId { get; set; }

    public DateOnly? StartDate { get; set; }

    public DateOnly? EndDate { get; set; }

    [StringLength(50)]
    public string Status { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? BudgetAmount { get; set; }

    [Column("CompanyID")]
    public int CompanyId { get; set; }

    [InverseProperty("Project")]
    public virtual ICollection<Apinvoice> Apinvoices { get; set; } = new List<Apinvoice>();

    [InverseProperty("Project")]
    public virtual ICollection<Arinvoice> Arinvoices { get; set; } = new List<Arinvoice>();

    [ForeignKey("CompanyId")]
    [InverseProperty("Projects")]
    public virtual Company Company { get; set; }

    [ForeignKey("CustomerId")]
    [InverseProperty("Projects")]
    public virtual Customer Customer { get; set; }

    [InverseProperty("Project")]
    public virtual ICollection<Document> Documents { get; set; } = new List<Document>();

    [InverseProperty("Project")]
    public virtual ICollection<EquipmentUsage> EquipmentUsages { get; set; } = new List<EquipmentUsage>();

    [InverseProperty("Project")]
    public virtual ICollection<ForecastedFinancial> ForecastedFinancials { get; set; } = new List<ForecastedFinancial>();

    [InverseProperty("Project")]
    public virtual ICollection<Kpi> Kpis { get; set; } = new List<Kpi>();

    [InverseProperty("Project")]
    public virtual ICollection<MaterialUsage> MaterialUsages { get; set; } = new List<MaterialUsage>();

    [InverseProperty("Project")]
    public virtual ICollection<ProjectFinancialSummary> ProjectFinancialSummaries { get; set; } = new List<ProjectFinancialSummary>();

    [ForeignKey("ProjectManagerId")]
    [InverseProperty("Projects")]
    public virtual Employee ProjectManager { get; set; }

    [InverseProperty("Project")]
    public virtual ICollection<PurchaseOrder> PurchaseOrders { get; set; } = new List<PurchaseOrder>();

    [InverseProperty("Project")]
    public virtual ICollection<Rfi> Rfis { get; set; } = new List<Rfi>();

    [InverseProperty("Project")]
    public virtual ICollection<TimeEntry> TimeEntries { get; set; } = new List<TimeEntry>();

    [InverseProperty("Project")]
    public virtual ICollection<Transmittal> Transmittals { get; set; } = new List<Transmittal>();
}