// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ERP_BI_Operations.Models;

[Table("ProjectFinancialSummary")]
public partial class ProjectFinancialSummary
{
    [Key]
    [Column("ProjectSummaryID")]
    public int ProjectSummaryId { get; set; }

    [Column("ProjectID")]
    public int ProjectId { get; set; }

    public DateOnly SummaryDate { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? ActualRevenue { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? ActualExpenses { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? ActualProfit { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? BudgetVariance { get; set; }

    [Column(TypeName = "decimal(5, 2)")]
    public decimal? PercentComplete { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? LaborCost { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? MaterialCost { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? EquipmentCost { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? SubcontractorCost { get; set; }

    [ForeignKey("ProjectId")]
    [InverseProperty("ProjectFinancialSummaries")]
    public virtual Project Project { get; set; }
}