// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ERP_BI_Operations.Models;

public partial class PurchaseOrderLine
{
    [Key]
    [Column("POLineID")]
    public int PolineId { get; set; }

    [Column("POID")]
    public int Poid { get; set; }

    [Column("MaterialID")]
    public int MaterialId { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal QuantityOrdered { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal UnitPrice { get; set; }

    [ForeignKey("MaterialId")]
    [InverseProperty("PurchaseOrderLines")]
    public virtual Material Material { get; set; }

    [ForeignKey("Poid")]
    [InverseProperty("PurchaseOrderLines")]
    public virtual PurchaseOrder Po { get; set; }
}