// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ERP_BI_Operations.Models;

public partial class PurchaseOrder
{
    [Key]
    [Column("POID")]
    public int Poid { get; set; }

    [Column("VendorID")]
    public int VendorId { get; set; }

    public DateOnly OrderDate { get; set; }

    public DateOnly? DeliveryDate { get; set; }

    [StringLength(50)]
    public string Status { get; set; }

    [Column("ProjectID")]
    public int? ProjectId { get; set; }

    [ForeignKey("ProjectId")]
    [InverseProperty("PurchaseOrders")]
    public virtual Project Project { get; set; }

    [InverseProperty("Po")]
    public virtual ICollection<PurchaseOrderLine> PurchaseOrderLines { get; set; } = new List<PurchaseOrderLine>();

    [ForeignKey("VendorId")]
    [InverseProperty("PurchaseOrders")]
    public virtual Vendor Vendor { get; set; }
}