// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ERP_BI_Operations.Models;

public partial class Receipt
{
    [Key]
    [Column("ReceiptID")]
    public int ReceiptId { get; set; }

    [Column("ARInvoiceID")]
    public int ArinvoiceId { get; set; }

    [Column("BankID")]
    public int BankId { get; set; }

    public DateOnly ReceiptDate { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal Amount { get; set; }

    [StringLength(100)]
    public string PaymentMethod { get; set; }

    [ForeignKey("ArinvoiceId")]
    [InverseProperty("Receipts")]
    public virtual Arinvoice Arinvoice { get; set; }

    [ForeignKey("BankId")]
    [InverseProperty("Receipts")]
    public virtual BankAccount Bank { get; set; }
}