// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ERP_BI_Operations.Models;

[Table("RFIs")]
public partial class Rfi
{
    [Key]
    [Column("RFIID")]
    public int Rfiid { get; set; }

    [Column("ProjectID")]
    public int ProjectId { get; set; }

    public DateOnly RequestDate { get; set; }

    public DateOnly? ResponseDate { get; set; }

    public int RequestedBy { get; set; }

    public string Description { get; set; }

    [StringLength(50)]
    public string Status { get; set; }

    [ForeignKey("ProjectId")]
    [InverseProperty("Rfis")]
    public virtual Project Project { get; set; }

    [ForeignKey("RequestedBy")]
    [InverseProperty("Rfis")]
    public virtual Employee RequestedByNavigation { get; set; }
}