// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ERP_BI_Operations.Models;

public partial class ServiceAgreement
{
    [Key]
    [Column("AgreementID")]
    public int AgreementId { get; set; }

    [Column("CustomerID")]
    public int CustomerId { get; set; }

    [StringLength(100)]
    public string AgreementType { get; set; }

    public DateOnly? StartDate { get; set; }

    public DateOnly? EndDate { get; set; }

    public string Terms { get; set; }

    [ForeignKey("CustomerId")]
    [InverseProperty("ServiceAgreements")]
    public virtual Customer Customer { get; set; }

    [InverseProperty("Agreement")]
    public virtual ICollection<ServiceOrder> ServiceOrders { get; set; } = new List<ServiceOrder>();
}