// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ERP_BI_Operations.Models;

public partial class ServiceOrder
{
    [Key]
    [Column("ServiceOrderID")]
    public int ServiceOrderId { get; set; }

    [Column("AgreementID")]
    public int? AgreementId { get; set; }

    [Column("CustomerID")]
    public int CustomerId { get; set; }

    [StringLength(255)]
    public string ServiceLocation { get; set; }

    public DateOnly RequestDate { get; set; }

    public DateOnly? CompletionDate { get; set; }

    [StringLength(50)]
    public string Status { get; set; }

    public string Description { get; set; }

    [Column("AssignedTechnicianID")]
    public int? AssignedTechnicianId { get; set; }

    [ForeignKey("AgreementId")]
    [InverseProperty("ServiceOrders")]
    public virtual ServiceAgreement Agreement { get; set; }

    [ForeignKey("AssignedTechnicianId")]
    [InverseProperty("ServiceOrders")]
    public virtual Employee AssignedTechnician { get; set; }

    [ForeignKey("CustomerId")]
    [InverseProperty("ServiceOrders")]
    public virtual Customer Customer { get; set; }
}