// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ERP_BI_Operations.Models;

public partial class TimeEntry
{
    [Key]
    [Column("TimeEntryID")]
    public int TimeEntryId { get; set; }

    [Column("EmployeeID")]
    public int EmployeeId { get; set; }

    [Column("ProjectID")]
    public int? ProjectId { get; set; }

    public DateOnly EntryDate { get; set; }

    [Column(TypeName = "decimal(5, 2)")]
    public decimal HoursWorked { get; set; }

    public string ActivityDescription { get; set; }

    [ForeignKey("EmployeeId")]
    [InverseProperty("TimeEntries")]
    public virtual Employee Employee { get; set; }

    [ForeignKey("ProjectId")]
    [InverseProperty("TimeEntries")]
    public virtual Project Project { get; set; }
}