// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ERP_BI_Operations.Models;

public partial class Transmittal
{
    [Key]
    [Column("TransmittalID")]
    public int TransmittalId { get; set; }

    [Column("ProjectID")]
    public int ProjectId { get; set; }

    public DateOnly TransmittalDate { get; set; }

    public int SentBy { get; set; }

    [StringLength(255)]
    public string Recipient { get; set; }

    public string Description { get; set; }

    [ForeignKey("ProjectId")]
    [InverseProperty("Transmittals")]
    public virtual Project Project { get; set; }

    [ForeignKey("SentBy")]
    [InverseProperty("Transmittals")]
    public virtual Employee SentByNavigation { get; set; }
}