// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ERP_BI_Operations.Models;

public partial class Vendor
{
    [Key]
    [Column("VendorID")]
    public int VendorId { get; set; }

    [Required]
    [StringLength(255)]
    public string VendorName { get; set; }

    [StringLength(255)]
    public string ContactPerson { get; set; }

    [StringLength(255)]
    public string Address { get; set; }

    [StringLength(100)]
    public string PaymentTerms { get; set; }

    [Column("CompanyID")]
    public int CompanyId { get; set; }

    [InverseProperty("Vendor")]
    public virtual ICollection<Apinvoice> Apinvoices { get; set; } = new List<Apinvoice>();

    [ForeignKey("CompanyId")]
    [InverseProperty("Vendors")]
    public virtual Company Company { get; set; }

    [InverseProperty("Vendor")]
    public virtual ICollection<PurchaseOrder> PurchaseOrders { get; set; } = new List<PurchaseOrder>();
}